### ISSUE TITLE
All Off routine

### ISSUE THREAD

**Issue by tonivanremortel** [joleys/niko-home-control-II#44] opened 2022-12-16 20:56 UTC
I have 2 All Off routines in my NHC2 setup. I see both 'buttons' in HA which I can press to start the routing in NHC2.
But I like to see when this routine runs on NHC2 (triggered by a physical Niko button) so I can use it as trigger to perform additional automation, like powering off music etc.
Can you add this? Should be possible if I read the Hobby API documentation.

**Comment by tijsverkoyen** [comment] 2022-12-20 15:16
The problem is that the All Off is somewhat weird component.

The state in the Niko Home app is either active of inactive. When all items in that are linked to the All Off are off then the state will be Active. So if you toggle all items off manually the state will change to Active. But this status change is not published. Actually it is, but the actual new state is not available.

I was thinking to switch the All Off to be a switch instead of a button. But the problem is that the state in Home Assistant won't be correct in some cases.

**Comment by user152306** [comment] 2022-12-27 12:10
> I have 2 All Off routines in my NHC2 setup. I see both 'buttons' in HA which I can press to start the routing in NHC2. But I like to see when this routine runs on NHC2 (triggered by a physical Niko button) so I can use it as trigger to perform additional automation, like powering off music etc. Can you add this? Should be possible if I read the Hobby API documentation.

A workaround would be to have an virtual entity within the NHC2 setup that is controlled by the routine, and then use the state  change of that entity to trigger automations in HA.

**Comment by tonivanremortel** [comment] 2023-01-20 21:35
Nice one!
I like to test it :-)

**Comment by tijsverkoyen** [comment] 2023-01-23 15:43
Feedback on the PR is welcome in: https://github.com/joleys/niko-home-control-II/pull/49

**Comment by tijsverkoyen** [comment] 2023-02-20 17:13
This will be resolved when https://github.com/joleys/niko-home-control-II/pull/49 is merged.

**Comment by tijsverkoyen** [comment] 2023-03-24 13:33
This is done in the [3.0.0 release](https://github.com/joleys/niko-home-control-II/releases/tag/3.0.0).

**Closed by tijsverkoyen** 2023-03-24 13:33 UTC
