### ISSUE TITLE
Shutters doens’t report final state after command

### ISSUE THREAD

**Issue by roelteeuwenNL** [joleys/niko-home-control-II#12] opened 2022-06-01 21:39 UTC
shutters doens’t report final state after command. So for example:

if the shutters receives command position to 10% then after reaching this position the device doesn’t report back that it has reached this state. Also for close (0%) and open (100%) state.
As soon as the stop button is manual pressed the shutter reports back it’s state.
Would be great of this could fix fixed somehow.

**Comment by tijsverkoyen** [comment] 2023-03-17 13:15
This is an issue in Niko Home Control 2 itself. 
If you use the up / down / stop buttons the new position is reported when it is finished. But is you use the slider to set the position it will not report back over MQTT.

I don't think there is much we can do about this.

**Comment by tijsverkoyen** [comment] 2023-03-27 11:21
@roelteeuwenNL does this answer your question?

**Comment by roelteeuwenNL** [comment] 2023-03-31 18:09
Thanks for replying @tijsverkoyen . Would it possible to report this to Niko? I'll send my contact this issue, maybe he can forward it to the Development time so they can fix it in the API.

**Comment by tijsverkoyen** [comment] 2023-04-03 09:44
@roelteeuwenNL I have reported this to Niko. But I can't guarantee anything.

There is maybe a way around this. But it will require some work: Store the requested position somewhere and when the Moving property changes update the position entity. Another option would be to use the optimistic mode for the sensor.

Could you verify that the Moving sensor is on just after you have set the position with the slide and it is Off when the position is reached? With that information I can work on the workaround hopefully

**Comment by tijsverkoyen** [comment] 2023-07-04 14:07
@roelteeuwenNL can you answer my question please?

**Comment by roelteeuwenNL** [comment] 2023-07-04 20:05
Hi Tijs, thanks for your fast reply. During the week I have no time to work on my NHC2 HAS project;) and the upcoming weekend I’m also quite busy with some renovations in my home. I’ll hope I can give you an update soon.Again thanks 🙏 very much for your support so far.Best regards RoelSent from my iPhoneOp 4 jul. 2023 om 16:07 heeft Tijs Verkoyen ***@***.***> het volgende geschreven:﻿
@roelteeuwenNL can you answer my question please?

**Comment by sgi3200** [comment] 2023-07-27 05:12
@tijsverkoyen I can confirm the last position is updating as expected and reports the correct state, whether I am using slider or button
<img width="421" alt="image" src="https://github.com/joleys/niko-home-control-II/assets/134430881/a70a5b46-3ce7-4936-b144-699e477b0b92">
<img width="421" alt="image" src="https://github.com/joleys/niko-home-control-II/assets/134430881/58c5af66-8e30-4903-bab3-a5040e984fa1">
<img width="422" alt="image" src="https://github.com/joleys/niko-home-control-II/assets/134430881/3317cf24-63ca-4016-99fd-6332c9cbee20">
<img width="416" alt="image" src="https://github.com/joleys/niko-home-control-II/assets/134430881/c0b1fa87-1aa2-4048-a890-3b996f462812">

I think you did a great job on this and this issue can be closed, thanks

**Comment by tijsverkoyen** [comment] 2023-07-27 06:44
Weird, I did not change anything :s
Maybe Niko did an update?
Can you doublecheck, and if everything is working correctly feel free to close this issue.

**Comment by sgi3200** [comment] 2023-07-27 14:33
checked all 11 blinds in my house and everything works like a charm, I cannot close this issue since I am not the author ;-)

**Closed** 2023-07-27 14:50 UTC
Labels: Waiting for feedback, Niko Home Control 2 issue

**Comment by roelteeuwenNL** [comment] 2023-07-30 12:04
I'm still didn't found time to work on my my NHC2 HAS setup, but great if this is working. When I find some time to do my setup I will also check this. Thanks guys 😁👍
