### ISSUE TITLE
Stops working

### ISSUE THREAD

**Issue by BalderikTheSecond** [joleys/niko-home-control-II#175] opened 2024-07-29 08:14 UTC
Installed the integration and it worked nicely. However, the integration stops working after a while. When I reload Home Assistant, the integration works again - for a while. I have not found the specific trigger that causes the issue. I don't have any issues with other integrations. 

I am on the latest versions of the integration (v4.4.1) and HA (Core 2024.7.3, Supervisor 2024.06.2).

**Comment by BalderikTheSecond** [comment] 2024-07-30 07:17
I enabled debug logging. I get a really long list of DEBUG records in the home-assistant.log. Most look like this:

2024-07-29 18:31:53.131 DEBUG (Thread-3 (_thread_main)) [custom_components.nhc2.nhccoco.devices.controller] Controller changed (1bcb7a07-aa72-4948-9bab-fec0fcd41049/control/devices/evt == /control/devices/rsp).
2024-07-29 18:31:53.131 DEBUG (Thread-3 (_thread_main)) [custom_components.nhc2.nhccoco.devices.device] energyhome changed. Topic: 1bcb7a07-aa72-4948-9bab-fec0fcd41049/control/devices/evt | Data: {'Uuid': '516c1d4e-f853-4e29-bebd-ceee591869fd', 'Properties': [{'ReportInstantUsage': 'False'}]}
2024-07-29 18:31:53.155 DEBUG (Thread-2 (_publish_device_control_commands)) [custom_components.nhc2.nhccoco.coco] → Publishing device control command: {"Method": "devices.control", "Params": [{"Devices": [{"Uuid": "516c1d4e-f853-4e29-bebd-ceee591869fd", "Properties": [{"ReportInstantUsage": "True"}]}]}]}
2024-07-29 18:31:53.241 DEBUG (Thread-3 (_thread_main)) [custom_components.nhc2.nhccoco.devices.controller] Controller changed (1bcb7a07-aa72-4948-9bab-fec0fcd41049/control/devices/evt == /control/devices/rsp).
2024-07-29 18:31:53.241 DEBUG (Thread-3 (_thread_main)) [custom_components.nhc2.nhccoco.devices.device] energyhome changed. Topic: 1bcb7a07-aa72-4948-9bab-fec0fcd41049/control/devices/evt | Data: {'Uuid': '516c1d4e-f853-4e29-bebd-ceee591869fd', 'Properties': [{'ReportInstantUsage': 'True'}]}

Could that be the root cause or is there anything else to look out for?  (there are 8000 records in 24h)

**Comment by tijsverkoyen** [comment] 2024-08-07 13:36
The logs really indicate that the integration is working ;-)
The lines you have pasted are the reanbling of `ReportInstantUsage` for the energy home. See https://github.com/joleys/niko-home-control-II?tab=readme-ov-file#i-see-a-lot-of-report-instant-usage-re-enabled-messages-in-the-log

You can disable this by switching the "Disable Report Instant Usage Re-enabling Switch" to on on the Energy Home device in Home Assistant.

So this is not really the issue.

**Comment by ellvinib** [comment] 2024-08-26 21:43
I have the same issue, and the issue is present in previous Versions. I Just restart my HA and it works again.

**Comment by BalderikTheSecond** [comment] 2024-08-30 13:28
> The logs really indicate that the integration is working ;-) The lines you have pasted are the reanbling of `ReportInstantUsage` for the energy home. See https://github.com/joleys/niko-home-control-II?tab=readme-ov-file#i-see-a-lot-of-report-instant-usage-re-enabled-messages-in-the-log
> 
> You can disable this by switching the "Disable Report Instant Usage Re-enabling Switch" to on on the Energy Home device in Home Assistant.
> 
> So this is not really the issue.

Thanks @tijsverkoyen. I disabled the reporting but have not been able to find the reason yet in the logs.

So far I have been running HA in docker on a Synology NAS. I am not sure if that can cause issues?

I am planning to get a dedicated mini pc with HAOS. Let's see if that works better.

**Comment by BalderikTheSecond** [comment] 2024-09-03 10:41
@tijsverkoyen I did a clean install over the weekend and have not been able to recreate the issue yet. Let's hope it stays like this.

The only error I find after installation is the following:

Logger: homeassistant.util.loop
Source: util/loop.py:77
First occurred: September 2, 2024 at 9:36:32 PM (1 occurrences)
Last logged: September 2, 2024 at 9:36:32 PM

Detected blocking call to import_module with args ('custom_components.nhc2',) in /usr/src/homeassistant/homeassistant/loader.py, line 1067: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component component = await integration.async_get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component comp = self._get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component ComponentProtocol, importlib.import_module(self.pkg_path)

**Comment by tijsverkoyen** [comment] 2024-09-04 19:24
Ok. I will close this issue.

**Closed by tijsverkoyen** 2024-09-04 19:24 UTC
Labels: Waiting for feedback
